import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useDemo } from '../store/DemoContext';
import { generateCommunications, generateSpeech, generateSubjectLine } from '../services/gemini';
import { Mail, MessageSquare, Calendar, ChevronRight, Loader2, Activity, Volume2, VolumeX, Send, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';

export const Communications = () => {
  const navigate = useNavigate();
  const { currentPatient, setCurrentPatient, updatePatient } = useDemo();
  const [isGenerating, setIsGenerating] = useState(true);
  const [comms, setComms] = useState<any>(null);
  const [activeTab, setActiveTab] = useState<'email' | 'sms'>('email');
  const [activeEmailIndex, setActiveEmailIndex] = useState(0);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [audioUrls, setAudioUrls] = useState<Record<string, string>>({});
  const [sendingEmail, setSendingEmail] = useState(false);
  const [sendingSms, setSendingSms] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [smsSent, setSmsSent] = useState(false);
  const [isGeneratingSubject, setIsGeneratingSubject] = useState(false);

  const handleGenerateSubject = async () => {
    setIsGeneratingSubject(true);
    const activeEmail = comms.emails[activeEmailIndex];
    const newSubject = await generateSubjectLine(currentPatient, activeEmail.type, activeEmail.body);
    
    setComms((prev: any) => {
      const newComms = { ...prev };
      newComms.emails = [...prev.emails];
      newComms.emails[activeEmailIndex] = {
        ...newComms.emails[activeEmailIndex],
        subject: newSubject
      };
      
      // Also update the global patient state
      updatePatient(currentPatient.id!, { communications: newComms });
      setCurrentPatient({ ...currentPatient, communications: newComms });
      
      return newComms;
    });
    setIsGeneratingSubject(false);
  };

  useEffect(() => {
    const fetchComms = async () => {
      // Simulate network delay for effect
      await new Promise(resolve => setTimeout(resolve, 1500));

      if (currentPatient.firstName) {
        let result = await generateCommunications(currentPatient);
        if (result && result.emails && result.emails.length > 0) {
          
          // Dynamically generate subject lines for each email using the dedicated function
          try {
            const subjectPromises = result.emails.map((email: any) => 
              generateSubjectLine(currentPatient, email.type, email.body)
            );
            const dynamicSubjects = await Promise.all(subjectPromises);
            
            result.emails = result.emails.map((email: any, index: number) => ({
              ...email,
              subject: dynamicSubjects[index]
            }));
          } catch (e) {
            console.error("Failed to generate dynamic subject lines:", e);
            // Fallback to the subjects generated by generateCommunications
          }

          setComms(result);
          setCurrentPatient({ ...currentPatient, communications: result });
          if (currentPatient.id) {
            updatePatient(currentPatient.id, { communications: result });
          }
        } else {
          // Fallback mock data
          const fallback = {
            emails: [
              { type: 'Welcome Email', day: 1, subject: `Welcome to Your Wellness Journey, ${currentPatient.firstName || 'Friend'}`, body: `<p>Hi ${currentPatient.firstName || 'there'},</p><p>Thank you for your interest in ${currentPatient.interest || 'our wellness programs'}. We are excited to support your lifestyle goals.</p><p>Our clinician-led approach focuses on individualized strategies to help you optimize your potential. This educational sequence will provide you with valuable information over the coming weeks.</p><p>Ready to take the next step? Schedule a brief consultation to discuss your specific needs.</p>` },
              { type: 'What To Expect', day: 3, subject: 'What to Expect from Our Clinic', body: `<p>Hi ${currentPatient.firstName || 'there'},</p><p>When you visit our clinic, our focus is entirely on your individualized wellness journey. We use data-driven insights to support your goals.</p><p>Schedule a consultation today to learn more.</p>` },
              { type: 'Wellness Education', day: 7, subject: `Educational Insights: ${currentPatient.interest || 'Wellness'}`, body: `<p>Hi ${currentPatient.firstName || 'there'},</p><p>Did you know that optimizing your daily routines can significantly impact your overall vitality? Small changes can lead to noticeable improvements in how you feel.</p><p>Let's discuss how this applies to you. Schedule an appointment below.</p>` },
              { type: 'FAQ / Objections', day: 14, subject: 'Common Questions Answered', body: `<p>Hi ${currentPatient.firstName || 'there'},</p><p>Many people wonder if our approach is right for them. Our programs are designed to be flexible and supportive of your unique lifestyle.</p><p>Have more questions? We'd love to chat. Schedule a consultation.</p>` },
              { type: 'Invitation To Schedule', day: 21, subject: 'Your Personalized Consultation Awaits', body: `<p>Hi ${currentPatient.firstName || 'there'},</p><p>You've learned a lot about our approach over the past few weeks. Now it's time to take action.</p><p>Schedule your clinician-led consultation today and let's build your individualized plan.</p>` }
            ],
            sms: [
              { type: 'Welcome SMS', body: `Hi ${currentPatient.firstName || 'there'}, thanks for connecting with our clinic regarding ${currentPatient.interest || 'wellness'}. Here is your scheduling link: clinic.demo/schedule. Reply STOP to opt out.` },
              { type: 'Reminder SMS', body: `Hi ${currentPatient.firstName || 'there'}, just a reminder that your personalized wellness plan is waiting. Schedule your consultation: clinic.demo/schedule. Reply STOP to opt out.` },
              { type: 'Follow-up SMS', body: `Hi ${currentPatient.firstName || 'there'}, we'd love to help you reach your ${currentPatient.interest || 'wellness'} goals. Let's chat: clinic.demo/schedule. Reply STOP to opt out.` }
            ]
          };
          setComms(fallback);
          setCurrentPatient({ ...currentPatient, communications: fallback });
        }
      } else {
        // Mock data if accessed directly
        const mock = {
          emails: [
            { type: 'Welcome Email', day: 1, subject: 'Welcome to Your Wellness Journey, John', body: '<p>Hi John,</p><p>Thank you for your interest in Recovery and Performance. We are excited to support your lifestyle goals.</p><p>Our clinician-led approach focuses on individualized strategies to help you optimize your potential. This educational sequence will provide you with valuable information over the coming weeks.</p><p>Ready to take the next step? Schedule a brief consultation to discuss your specific needs.</p>' },
            { type: 'What To Expect', day: 3, subject: 'What to Expect from Our Clinic', body: '<p>Hi John,</p><p>When you visit our clinic, our focus is entirely on your individualized wellness journey. We use data-driven insights to support your goals.</p><p>Schedule a consultation today to learn more.</p>' },
            { type: 'Wellness Education', day: 7, subject: 'Educational Insights: Recovery and Performance', body: '<p>Hi John,</p><p>Did you know that optimizing your daily routines can significantly impact your overall vitality? Small changes can lead to noticeable improvements in how you feel.</p><p>Let\'s discuss how this applies to you. Schedule an appointment below.</p>' },
            { type: 'FAQ / Objections', day: 14, subject: 'Common Questions Answered', body: '<p>Hi John,</p><p>Many people wonder if our approach is right for them. Our programs are designed to be flexible and supportive of your unique lifestyle.</p><p>Have more questions? We\'d love to chat. Schedule a consultation.</p>' },
            { type: 'Invitation To Schedule', day: 21, subject: 'Your Personalized Consultation Awaits', body: '<p>Hi John,</p><p>You\'ve learned a lot about our approach over the past few weeks. Now it\'s time to take action.</p><p>Schedule your clinician-led consultation today and let\'s build your individualized plan.</p>' }
          ],
          sms: [
            { type: 'Welcome SMS', body: 'Hi John, thanks for connecting with our clinic. Here is your scheduling link: clinic.demo/schedule. Reply STOP to opt out.' },
            { type: 'Reminder SMS', body: 'Hi John, just a reminder that your personalized wellness plan is waiting. Schedule your consultation: clinic.demo/schedule. Reply STOP to opt out.' },
            { type: 'Follow-up SMS', body: 'Hi John, we\'d love to help you reach your Recovery and Performance goals. Let\'s chat: clinic.demo/schedule. Reply STOP to opt out.' }
          ]
        };
        setComms(mock);
      }
      setIsGenerating(false);
    };

    fetchComms();
  }, []);

  const handleSpeak = async (text: string, id: string) => {
    if (isSpeaking) {
      setIsSpeaking(false);
      return;
    }

    if (audioUrls[id]) {
      const audio = new Audio(audioUrls[id]);
      audio.onended = () => setIsSpeaking(false);
      audio.play();
      setIsSpeaking(true);
      return;
    }

    const cleanText = text.replace(/<[^>]*>/g, ''); // Remove HTML tags
    const url = await generateSpeech(cleanText);
    if (url) {
      setAudioUrls(prev => ({ ...prev, [id]: url }));
      const audio = new Audio(url);
      audio.onended = () => setIsSpeaking(false);
      audio.play();
      setIsSpeaking(true);
    }
  };

  const handleSendEmail = async () => {
    if (!currentPatient.email) {
      alert("No email address provided for this patient.");
      return;
    }
    
    setSendingEmail(true);
    try {
      const emailContent = comms.emails[0]; // Welcome Email
      const response = await fetch('/api/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: currentPatient.email,
          subject: emailContent.subject,
          html: emailContent.body
        })
      });
      
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to send email');
      }
      
      setEmailSent(true);
      if (currentPatient.id) {
        updatePatient(currentPatient.id, {
          timeline: [
            ...(currentPatient.timeline || []),
            { date: new Date().toISOString(), event: 'Welcome Email Sent' }
          ]
        });
      }
    } catch (error: any) {
      alert(`Error sending email: ${error.message}. Please check your .env configuration.`);
    } finally {
      setSendingEmail(false);
    }
  };

  const handleSendSms = async () => {
    if (!currentPatient.phone) {
      alert("No phone number provided for this patient.");
      return;
    }
    
    setSendingSms(true);
    try {
      const smsContent = comms.sms[0]; // Welcome SMS
      const response = await fetch('/api/send-sms', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: currentPatient.phone,
          body: smsContent.body
        })
      });
      
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to send SMS');
      }
      
      setSmsSent(true);
      if (currentPatient.id) {
        updatePatient(currentPatient.id, {
          timeline: [
            ...(currentPatient.timeline || []),
            { date: new Date().toISOString(), event: 'Welcome SMS Sent' }
          ]
        });
      }
    } catch (error: any) {
      alert(`Error sending SMS: ${error.message}. Please check your .env configuration.`);
    } finally {
      setSendingSms(false);
    }
  };

  return (
    <div className="flex-1 bg-gray-50 flex flex-col items-center py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl w-full space-y-8">
        
        <div className="text-center">
          <h2 className="text-3xl font-bold text-gray-900">Automated Communications</h2>
          <p className="mt-2 text-gray-500">
            The system automatically generates a compliant, educational follow-up sequence.
          </p>
        </div>

        <div className="bg-white rounded-3xl shadow-sm border border-gray-200 overflow-hidden">
          {/* Tabs */}
          <div className="flex border-b border-gray-200">
            <button
              onClick={() => setActiveTab('email')}
              className={`flex-1 py-4 px-6 text-center font-medium text-sm flex items-center justify-center transition-colors ${
                activeTab === 'email' ? 'bg-indigo-50 text-indigo-700 border-b-2 border-indigo-500' : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
              }`}
            >
              <Mail className="w-5 h-5 mr-2" />
              Email Sequence
            </button>
            <button
              onClick={() => setActiveTab('sms')}
              className={`flex-1 py-4 px-6 text-center font-medium text-sm flex items-center justify-center transition-colors ${
                activeTab === 'sms' ? 'bg-indigo-50 text-indigo-700 border-b-2 border-indigo-500' : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
              }`}
            >
              <MessageSquare className="w-5 h-5 mr-2" />
              SMS Sequence
            </button>
          </div>

          <div className="p-8">
            {isGenerating ? (
              <div className="flex flex-col items-center justify-center py-24 space-y-4">
                <Loader2 className="w-12 h-12 text-indigo-600 animate-spin" />
                <p className="text-gray-500 font-medium animate-pulse">Generating compliant communications...</p>
              </div>
            ) : (
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
              >
                {activeTab === 'email' && comms?.emails && (
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                    {/* Sidebar Sequence List */}
                    <div className="col-span-1 space-y-2 border-r border-gray-100 pr-4">
                      {comms.emails.map((email: any, index: number) => (
                        <div 
                          key={index}
                          onClick={() => setActiveEmailIndex(index)}
                          className={`p-3 border rounded-xl cursor-pointer transition-colors ${
                            activeEmailIndex === index 
                              ? 'bg-indigo-50 border-indigo-200' 
                              : 'bg-white border-gray-100 opacity-60 hover:opacity-100'
                          }`}
                        >
                          <p className={`text-xs font-semibold ${activeEmailIndex === index ? 'text-indigo-800' : 'text-gray-500'}`}>Day {email.day}</p>
                          <p className={`text-sm font-medium ${activeEmailIndex === index ? 'text-indigo-900' : 'text-gray-700'}`}>{email.type}</p>
                        </div>
                      ))}
                    </div>

                    {/* Email Preview Pane */}
                    <div className="col-span-3 bg-gray-50 rounded-2xl border border-gray-200 overflow-hidden flex flex-col">
                      <div className="bg-white border-b border-gray-200 p-4 flex justify-between items-center">
                        <div>
                          <div className="flex items-center justify-between mb-2">
                            <span className="text-sm font-medium text-gray-500">From: Clinic Wellness Team</span>
                            <span className="text-xs text-gray-400">Day {comms.emails[activeEmailIndex]?.day}</span>
                          </div>
                          <div className="flex items-center gap-3">
                            <h4 className="text-lg font-semibold text-gray-900">
                              {comms.emails[activeEmailIndex]?.subject}
                            </h4>
                            <button
                              onClick={handleGenerateSubject}
                              disabled={isGeneratingSubject}
                              title="Generate new subject line with AI"
                              className="p-1.5 text-indigo-500 hover:bg-indigo-50 hover:text-indigo-700 rounded-lg transition-colors disabled:opacity-50"
                            >
                              {isGeneratingSubject ? (
                                <Loader2 className="w-4 h-4 animate-spin" />
                              ) : (
                                <Sparkles className="w-4 h-4" />
                              )}
                            </button>
                          </div>
                        </div>
                        <button
                          onClick={() => handleSpeak(comms.emails[activeEmailIndex]?.body, `email-${activeEmailIndex}`)}
                          className={`p-3 rounded-xl transition-all ${
                            isSpeaking 
                              ? 'bg-red-100 text-red-600' 
                              : 'bg-indigo-100 text-indigo-600 hover:bg-indigo-200'
                          }`}
                        >
                          {isSpeaking ? <VolumeX className="w-5 h-5" /> : <Volume2 className="w-5 h-5" />}
                        </button>
                      </div>
                      <div className="p-6 flex-1 bg-white">
                        <div 
                          className="prose prose-sm prose-indigo max-w-none text-gray-700"
                          dangerouslySetInnerHTML={{ __html: comms.emails[activeEmailIndex]?.body }}
                        />
                        
                        <div className="mt-8 pt-6 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-center gap-4">
                          {activeEmailIndex === 0 && (
                            <button
                              onClick={handleSendEmail}
                              disabled={sendingEmail || emailSent}
                              className={`inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-lg shadow-sm text-white transition-all ${
                                emailSent 
                                  ? 'bg-green-600 hover:bg-green-700' 
                                  : 'bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500'
                              } disabled:opacity-50 disabled:cursor-not-allowed`}
                            >
                              {sendingEmail ? (
                                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                              ) : (
                                <Send className="w-4 h-4 mr-2" />
                              )}
                              {emailSent ? 'Welcome Email Sent' : 'Send Welcome Email'}
                            </button>
                          )}
                          <button
                            onClick={() => navigate('/scheduling')}
                            className="inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-lg shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                          >
                            <Calendar className="w-4 h-4 mr-2" />
                            Schedule Appointment
                          </button>
                        </div>
                      </div>
                      <div className="bg-gray-100 p-4 text-center">
                        <p className="text-[10px] text-gray-500 leading-tight">
                          This email is for educational purposes only and does not constitute medical advice. Results vary. Not intended to diagnose, treat, cure, or prevent any disease.
                        </p>
                      </div>
                    </div>
                  </div>
                )}

                {activeTab === 'sms' && comms?.sms && (
                  <div className="flex flex-col items-center">
                    {/* Phone Mockup */}
                    <div className="relative w-[320px] h-[650px] bg-gray-900 rounded-[3rem] border-[12px] border-gray-900 shadow-2xl overflow-hidden flex flex-col">
                      {/* Notch */}
                      <div className="absolute top-0 inset-x-0 h-6 bg-gray-900 rounded-b-3xl w-40 mx-auto z-20"></div>
                      
                      {/* Screen */}
                      <div className="flex-1 bg-gray-100 flex flex-col relative z-10">
                        {/* Header */}
                        <div className="bg-gray-100/80 backdrop-blur-md pt-12 pb-4 px-4 border-b border-gray-200 sticky top-0 z-10 flex items-center justify-center">
                          <div className="flex flex-col items-center">
                            <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center mb-1">
                              <Activity className="w-5 h-5 text-indigo-600" />
                            </div>
                            <span className="text-xs font-semibold text-gray-900">Clinic Wellness</span>
                          </div>
                        </div>

                        {/* Messages */}
                        <div className="flex-1 p-4 overflow-y-auto space-y-4 flex flex-col justify-end pb-8">
                          {comms.sms.map((msg: any, index: number) => (
                            <div key={index} className="flex flex-col items-start group">
                              <div className="flex items-center justify-between w-full mb-1">
                                <span className="text-[10px] text-gray-400 ml-2">{msg.type}</span>
                                <button 
                                  onClick={() => handleSpeak(msg.body, `sms-${index}`)}
                                  className="opacity-0 group-hover:opacity-100 transition-opacity p-1 text-indigo-600"
                                >
                                  <Volume2 className="w-3 h-3" />
                                </button>
                              </div>
                              <div className="bg-white text-gray-900 p-3 rounded-2xl rounded-tl-sm shadow-sm text-sm max-w-[85%] border border-gray-200 leading-snug">
                                {msg.body}
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                    <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
                      <button
                        onClick={handleSendSms}
                        disabled={sendingSms || smsSent}
                        className={`inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-lg shadow-sm text-white transition-all ${
                          smsSent 
                            ? 'bg-green-600 hover:bg-green-700' 
                            : 'bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500'
                        } disabled:opacity-50 disabled:cursor-not-allowed`}
                      >
                        {sendingSms ? (
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        ) : (
                          <Send className="w-4 h-4 mr-2" />
                        )}
                        {smsSent ? 'Welcome SMS Sent' : 'Send Welcome SMS'}
                      </button>
                      <button
                        onClick={() => navigate('/scheduling')}
                        className="inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-lg shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                      >
                        <Calendar className="w-4 h-4 mr-2" />
                        Schedule Appointment
                      </button>
                    </div>
                  </div>
                )}
              </motion.div>
            )}
          </div>
        </div>

        <div className="flex justify-center">
          <button
            onClick={() => navigate('/scheduling')}
            className="inline-flex items-center justify-center px-8 py-4 border border-transparent text-lg font-medium rounded-full shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-all"
          >
            Continue to Scheduling
            <ChevronRight className="ml-2 w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

